force-app/main/default/objects/Account/fields/JIRA_Project_Key__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Project_Key__c</fullName>
    <label>JIRA Project Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/JIRA_Project_Lead__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Project_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>JIRA Project Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/JIRA_Project_Name__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Project_Name__c</fullName>
    <label>JIRA Project Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/project/JIRAProjectController.cls
public class JIRAProjectController {
    public Id accId {get;set;}
    public Account acc {get;set;}
    
    public JIRAProjectController(ApexPages.StandardController controller) {
        accId = controller.getRecord().Id;
        acc = [SELECT Id, Name, JIRA_Project_Key__c, JIRA_Project_Id__c, JIRA_Project_Name__c, JIRA_Project_Lead__c,
        JIRA_Project_Lead__r.JIRA_User_Id__c FROM Account WHERE Id =: accId];

        if(acc.JIRA_Project_Lead__c == null) {
            throw new JIRAException('Please select a project lead');
        }
    }
    
    public PageReference createProject(){
        JIRAProjectHelper.createOrUpdateProject(acc, acc.JIRA_Project_Lead__r.JIRA_User_Id__c);
        update acc;
        return new PageReference('/'+ accId);
    }
}